sudo: required
services:
  - docker

# Do these steps before we start running our test suites
before_install:
  - docker build -t rinorsadiku/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rinorsadiku/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: elasticbeanstalk-eu-central-1-117778104912
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
